### PR TITLE
Create singleton pattern using c# language

### PR DESCRIPTION
**Pull request by kuljit95**
1. Create the singleton class
2. Add example to explain singleton method 
3.  Create second instance to compare with first instance

### CODE REVIEW

**Comment by mijuanmontalvo** [comment]
Hi @kuljit95, how are you, I have only an observation about your pull request, I think it is good idea including in the title of pull request or in the description of pull request the number of issue.

This is simply to be clearer about what issue the pull request is working on.

**Comment by ash-teach** [comment]
@kuljit95 - Thanks for starting work on this. However, the code does not compile. Please retest and fix.

**Comment by ash-teach** [comment]
Perhaps @Ravi-takhi can give you a hand, since he's comfortable with C#.

**Comment by kuljit95** [comment]
Thankyou @ash-teach for feedback. I'm working on it.

**Comment by kuljit95** [comment]
thankyou @mijuanmontalvo for advice.

**Comment by Ravi-takhi** [comment]
@kuljit95, I just checked your code and I got some compilation errors.

``` csharp
private static readonly Calculationsinstance = new Calculations();
    static Calculations()

```

While creating the object you should mention the class name just before your  class instance.
#### For example
``` csharp
private static readonly Calculations Calculationsinstance = new Calculations();
    static Calculations()

```
Change according to that.

**Comment by kuljit95** [comment]
Thankyou @Ravi-takhi . I will make changes according to your feedback.

**Comment by kuljit95** [comment]
Make changes according to the feedback

**Pull request merged**
