### PR TITLE
Add React Native implementation for Singleton pattern #8

### PR DESCRIPTION
**Pull request by Anjitha-94**

### CODE REVIEW

**Review by Dhuds1 — COMMENTED** [review]
Hey!

I am not overly familiar with react native, or with the singleton pattern, but I've read your code a bunch and it looks very clean! I am curious on why you decided to make the objects properties possessive ex: `MySingleton` `myProperty` `myMethod()`? 

Lastly, I know the singleton is supposed to only have one instance, but have you considered making it mutable? Or is it just supposed to be immutable?

Nice work, and clean code!

**Comment by ash-teach** [comment]
@Anjitha-94 - I think this implementation is really quite similar to what we have already in the [JS Singleton patterns](https://github.com/nic-dgl104-winter-2024/pattern-library/tree/main/patterns/Creational/singleton/JavaScript). 

Of course, it is to be expected that there is some overlap between a React Native implementation and a JavaScript implementation. However, what I was hoping for from a React Native specific implementation was to use more of the available React framework in support. 

Honestly, I'm not sure if that's even reasonable, since I don't have much experience in React Native myself. Could you do a bit of research however to determine if there is any other way to write Singleton with any React Native-specific tools? If not, then perhaps we don't need this particular implementation.

Feel free to invite others to help you out with this - especially anyone who knows React Native already. I've added the 'help-wanted' tag to indicate that others should chime in if they have anything to share.

**Comment by Ravi-takhi** [comment]
hi @Anjitha-94 
I just gone through your code I got 2 feedback point for your project.

Point 1:- 

``` javascript

constructor() {
    if (MySingleton.instance !== null) {
      throw new Error("Singleton instance already exists. Use getInstance method.");
    }

    // Initialize properties
    this.myProperty = "Initial Value";

    MySingleton.instance = this;
    Object.freeze(MySingleton.instance); // Ensure the instance is immutable
  }

// Static method to get instance
  static getInstance() {
    if (!MySingleton.instance) {
      MySingleton.instance = new MySingleton();
    }
    return MySingleton.instance;
  }
```
 Making an instance inside the constructor and doing it again in the getInstance method is kind of doing the same thing twice, which isn't necessary. 

Point 2:-
  Also, it's not great to use a return statement in a constructor. Removing it won't change how the code works,

**Comment by Anjitha-94** [comment]
Hai @Ravi-takhi
 I have corrected it with your suggestion thank you for your help

**Comment by ash-teach** [comment]
@Anjitha-94 - the code as presented doesn't work properly. I think that you should perhaps run through some tests to determine the best way to proceed with a fix. It seems you've made attempts to try a couple different approaches, but they don't seem to be fully compatible. In particular, I think you should examine the use of the first conditional check in the `constructor` and the use of `Object.freeze`.

**Pull request closed without merging**
