### PR TITLE
[Do not marge] Add definition of MVC pattern in README.md

### PR DESCRIPTION
**Pull request by michiwo1**
## Note
This content may be included in the pull request in #41, so it may no longer be necessary. 
https://github.com/nic-dgl104-winter-2024/pattern-library/pull/42/files/93a5af6296d829bed45f61a41174af8883c0e8c7#diff-4938c2baf5216f73d4ec6059d4abfad33b67b3b4887eb22d53e949785a9d33d9

## Related Issue
#24 

## Description
Write definition of MVC pattern in README.md
-  Identify one or more appropriate references.
- Write one or two or three paragraphs describing the purpose of the MVC architectural pattern (no code necessary).
- Include well-formatted references (either immediately following the description, or in a references section).

## Changes
- I added definition of MVC pattern to readme

### CODE REVIEW

**Comment by michiwo1** [comment]
Hi @ash-teach,

Does this pull request need to be reviewed before merging?
If so, please review if necessary.
I have added this to the readme, but I am not sure if this is the correct way to write it. If I am writing it incorrectly, please comment so I can correct it.
Also, if this pull request is merged, will my Community Code Project part2 be finished?

**Comment by ash-teach** [comment]
Thanks, @michiwo1, I'll encourage other students to review. Once the review is complete I will merge.

As for whether your work in Part 2 is done: I would say probably not. The expectation is that you put ~4 hours per week between weeks 9 and 12 on this project (split between both parts 1 and 2). Looking at this pull request I would guess you might have spent a couple hours total on it? You should find some other issues to contribute to - or PRs to review.

**Comment by ash-teach** [comment]
Hi @michiwo1  - I just wanted to confirm with you that even though this PR was closed, and that the work assigned here was adopted by #51, the work you did is **still very much valid** and counts as work done towards Part 2 of the community code project. So please do note that work that you've done here as part of this PR in your research and reflection journal!

**Comment by michiwo1** [comment]
Hi @ash-teach,
I understand.
Should #24 be closed?

**Pull request closed without merging**
