### PR TITLE
Add javascript singleton document

### PR DESCRIPTION
**Pull request by ting-dev-coder**
## Status
Done

## Description
Document for singleton in javascript #2 

## Breaking Changes
No
## Type of Change
📝 Code

### CODE REVIEW

**Comment by ting-dev-coder** [comment]
I'm not sure if this is the correct approach for this issue. I've created a document for the singleton pattern in JavaScript
@ash-teach whether we only need code or if both documentation and code are acceptable?

**Comment by ash-teach** [comment]
Great work! I'll offer this as a suggestion, and let's discuss and see what direction we go:

I had imagined that the individual pattern library folders (i.e. `pattern/javascript` in this case) would contain a single implementation of the specified pattern written in a code-specific file (i.e. '.js' in this case, rather than in '.md' files). Each of these files could contain in-code comments to clarify points, but I didn't imagine that we would include README.md files for _each_ implementation. 

Rationale: Layers of documentation become very difficult to maintain. What I'd like to see is some high-level language-agnostic documentation for each pattern (see #20, for example), that includes a list of links pointing directly to implementations in their respective folders. I think this is easier to maintain, and easier to understand from a high-level concept. It should also reduce redundancy, since if we include documentation with each implementation we'll repeat ourselves quite lot!

What do you think?

**Comment by ash-teach** [comment]
Also, there is no requirement to stick to just one implementation per pattern per language. I see in your PR that you have a couple implementations for singleton: We could then include multiple '.js' files, one for each implementation.

**Comment by ting-dev-coder** [comment]
I agree! 
Having README.md files may lead to maintenance issues, whether in a single file or a file structure.
I think in this case, it involves a few issues here (#1, #2, #30). 
Let me wrap this document into a code version, and how about discussing the file structure in another commit?

**Pull request merged**
