### PR TITLE
Abstract Factory and  design patters folder estructure

### PR DESCRIPTION
**Pull request by john24alex**
To cover the Identify a potential short list of additional design patterns #26 issue, I did this:

- I Created inside the patterns directory the readme with the index and the explanation of all the patterns and the idea is to redirect from that index to each pattern.

- Also, I created the abstract-factory directory with its readme file explaining the pattern and the code example.

- I modified the main readme adding the explanation of the design pattern and the link to the content inside the readme the patterns directory.

- I have a suggestion and that is to move the content of the Definition of Observer Pattern which is in the main readme to the directory of Observer Pattern inside the patterns directory.

### CODE REVIEW

**Comment by ash-teach** [comment]
@john24alex - this is great work! Can you please also include any references that you used as part of your research? Please include them in comments in appropriate files (i.e. Abstract Factory README and .js file).

**Comment by ash-teach** [comment]
Note that I've merged your README.md changes that were in conflict in this PR with main. I think if you update this it won't cause too much trouble for you - but if you run into any issues, I can merge this first and then you can update references in a second PR.

**Comment by john24alex** [comment]
Hi @ash-teach  sure, let me update the info requested and update the PR
Thanks

**Comment by john24alex** [comment]
@ash-teach  PR updated with your comments, let me know any comments, @mijuanmontalvo once the PR is approved you can upload your part

**Pull request merged**
