### PR TITLE
[add] Java implementation for Singleton pattern

### PR DESCRIPTION
**Pull request by Abdulrahman295**

### CODE REVIEW

**Comment by ash-teach** [comment]
Hi @Abdulrahman295 - what was your source for this code? Did you write it yourself, or did you write it with reference to published material?

**Comment by Abdulrahman295** [comment]
@ash-teach 
The following are the references I used:

https://www.digitalocean.com/community/tutorials/java-singleton-design-pattern-best-practices-examples

https://refactoring.guru/design-patterns/singleton

**Comment by ash-teach** [comment]
Thanks, @Abdulrahman295. Can you include these in the header comments, if you've used them in developing the code?

**Comment by Abdulrahman295** [comment]
@ash-teach Done👍.

**Pull request merged**
